#################################
#           JoinEffect          #
#################################

# Hope you enjoy the plugin

# IF YOU NEED ADDITIONAL HELP VISIT THE BUKKIT DEV PAGE: http://dev.bukkit.org/bukkit-plugins/joineffect/

# Setting potion time to 99999 makes it infinite!

###############
# JUMP EFFECT #
###############

# Permission: joineffect.jump
# Recommended Jumpheight: 1-10

JumpEnabled: false
JumpHeight: 1
JumpTime: 999

################
# SPEED EFFECT #
################

# Permission: joineffect.speed
# Recommended SpeedLevel: 1-10

SpeedEnabled: false
SpeedLevel: 1
SpeedTime: 999

####################
# CONFUSION EFFECT #
####################

# Permission: joineffect.confusion
# Recommended ConfusionLevel: 1-10

ConfusionEnabled: true
ConfusionLevel: 10
ConfusionTime: 100

#################
# WITHER EFFECT #
#################

# Permission: joineffect.wither

WitherEnabled: false
WitherLevel: 1
WitherTime: 999

####################
# BLINDNESS EFFECT #
####################

# Permission: joineffect.blindness

BlindnessEnabled: true
BlindnessLevel: 2
BlindnessTime: 50

#################
# DAMAGE EFFECT #
#################

# Permission: joineffect.damage

DamageResistanceEnabled: false
DamageResistanceLevel: 1
DamageResistanceTime: 999

#######################
# FAST DIGGING EFFECT #
#######################
# Permission: joineffect.fastdigging

FastDiggingEnabled: false
FastDiggingLevel: 1
FastDiggingTime: 999

#########################
# FIRERESISTANCE EFFECT #
#########################

# Permission: joineffect.fireresistance

FireResitanceEnabled: false
FireResitanceLevel: 1
FireResitanceTime: 999

###############
# HARM EFFECT #
###############

# Permission: joineffect.harm

HarmEnabled: false
HarmLevel: 1
HarmTime: 999

###############
# HEAL EFFECT #
###############

# Permission: joineffect.heal

HealEnabled: false
HealLevel: 1
HealTime: 999

#################
# HUNGER EFFECT #
#################

# Permission: joineffect.hunger

HungerEnabled: false
HungerLevel: 1
HungerTime: 999

###################
# STRENGTH EFFECT #
###################

# Permission: joineffect.strength

StrenghtEnabled: false
StrengthLevel: 1
StrengthTime: 999

#######################
# INVISIBILITY EFFECT #
#######################

# Permission: joineffect.invisible

InvisibilityEnabled: false
InvisibilityLevel: 1
InvisibilityTime: 999

#######################
# NIGHT VISION EFFECT #
#######################

# Permission: joineffect.nightvision

NightVisionEnabled: false
NightVisionLevel: 1
NightVisionTime: 999

#################
# POISON EFFECT #
#################

# Permission: joineffect.poison

PoisonEnabled: false
PoisonLevel: 1
PoisonTime: 999

#######################
# REGENERATION EFFECT #
#######################

# Permission: joineffect.regeneration

RegenerationEnabled: false
RegenerationLevel: 1
RegenerationTime: 999

###################
# SLOWNESS EFFECT #
###################

# Permission: joineffect.slowness

SlownessEnabled: false
SlownessLevel: 1
SlownessTime: 999

######################
# SLOW MINING EFFECT #
######################

# Permission: joineffect.slowdigging

SlowDiggingEnabled: false
SlowDiggingLevel: 1
SlowDiggingTime: 999

##########################
# WATER BREATHING EFFECT #
##########################

# Permission: joineffect.waterbreathing

WaterBreathingEnabled: false
WaterBreathingLevel: 1
WaterBreathingTime: 999

###################
# WEAKNESS EFFECT #
###################

# Permission: joineffect.weakness

WeaknessEnabled: false
WeaknessLevel: 1
WeaknessTime: 999

##########################
# OTHER OPTIONS & EXTRAS #
##########################

# Permission: joineffect.remove
# Removes all current effects, adds above effects

#This option basically renews time each time a player joins

RemoveEffects: false